# Generated by Django 4.1.6 on 2023-02-22 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chairmanapp', '0008_chairman_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chairman',
            name='gender',
        ),
    ]
