# Generated by Django 4.1.6 on 2023-02-27 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chairmanapp', '0013_alter_registration_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='societymember',
            name='pic',
        ),
    ]
