# Generated by Django 4.1.6 on 2023-02-27 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chairmanapp', '0014_remove_societymember_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='societymember',
            name='blood_group',
        ),
        migrations.RemoveField(
            model_name='societymember',
            name='city',
        ),
        migrations.RemoveField(
            model_name='societymember',
            name='dob',
        ),
        migrations.RemoveField(
            model_name='societymember',
            name='house_ownership',
        ),
        migrations.RemoveField(
            model_name='societymember',
            name='no_of_familymembers',
        ),
        migrations.RemoveField(
            model_name='societymember',
            name='occupation',
        ),
        migrations.RemoveField(
            model_name='societymember',
            name='vehicle_details',
        ),
    ]
