# Generated by Django 4.1.6 on 2023-02-28 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chairmanapp', '0016_societymember_blood_group_societymember_city_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='societymember',
            name='city',
        ),
    ]
