# Generated by Django 4.1.6 on 2023-02-15 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chairmanapp', '0003_chairman_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='societymember',
            name='pic',
            field=models.FileField(default='media/default.png', upload_to='media/upload'),
        ),
    ]
