# Generated by Django 4.1.6 on 2023-02-21 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chairmanapp', '0006_notice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chairman',
            name='pic',
            field=models.FileField(default='media/default-female-pic.png', upload_to='media/upload'),
        ),
    ]
