# Generated by Django 4.1.6 on 2023-02-21 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chairmanapp', '0007_alter_chairman_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='chairman',
            name='gender',
            field=models.BooleanField(default=True),
        ),
    ]
