# Generated by Django 4.1.6 on 2023-02-28 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chairmanapp', '0015_remove_societymember_blood_group_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='societymember',
            name='blood_group',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='societymember',
            name='city',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='societymember',
            name='dob',
            field=models.DateField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='societymember',
            name='house_ownership',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='societymember',
            name='no_of_familymembers',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='societymember',
            name='occupation',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='societymember',
            name='pic',
            field=models.FileField(default='media/default.png', upload_to='media/upload'),
        ),
        migrations.AddField(
            model_name='societymember',
            name='vehicle_details',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
